"""models/media.py faylda MediaType default qilindi

Revision ID: 316fc246a470
Revises: 6b63fe20f83b
Create Date: 2025-12-28 14:00:12.184451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316fc246a470'
down_revision: Union[str, Sequence[str], None] = '6b63fe20f83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
