"""Media faylda o'zgarishlar

Revision ID: 899ee2bd4a98
Revises: 97b9142e0a0e
Create Date: 2026-01-01 12:03:30.196273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '899ee2bd4a98'
down_revision: Union[str, Sequence[str], None] = '97b9142e0a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('media', 'type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('video', 'audio', 'image', name='media_type_enum'),
               existing_nullable=False)
    op.alter_column('media', 'size',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('media', 'thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('media', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('uploading', 'uploaded', 'processing', 'failed', 'deleted', name='media_status_enum'),
               existing_nullable=False)
    op.drop_constraint(op.f('media_ibfk_1'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_ibfk_1'), 'media', 'users', ['owner_id'], ['id'])
    op.alter_column('media', 'status',
               existing_type=sa.Enum('uploading', 'uploaded', 'processing', 'failed', 'deleted', name='media_status_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('media', 'thumbnail',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('media', 'size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('media', 'type',
               existing_type=sa.Enum('video', 'audio', 'image', name='media_type_enum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('media', 'path',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
