"""add refresh_token and password_hash to user

Revision ID: 97b9142e0a0e
Revises: c0252bb1bec7
Create Date: 2025-12-31 15:58:11.127381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97b9142e0a0e'
down_revision: Union[str, Sequence[str], None] = 'c0252bb1bec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
